// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameTask = "t_task"

// Task mapped from table <t_task>
type Task struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Parameter string    `gorm:"column:parameter;not null" json:"parameter"`
	Image1    *[]byte   `gorm:"column:image1" json:"image1"`
	Image2    *[]byte   `gorm:"column:image2" json:"image2"`
	Image3    *[]byte   `gorm:"column:image3" json:"image3"`
	Image4    *[]byte   `gorm:"column:image4" json:"image4"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	UserID    int64     `gorm:"column:user_id;not null" json:"user_id"`
	Status    int32     `gorm:"column:status;not null;default:1" json:"status"`
	Message   *string   `gorm:"column:message" json:"message"`
}

// TableName Task's table name
func (*Task) TableName() string {
	return TableNameTask
}
